// Execute only in an isolated authenticated QA app. PDFs are synthetic fixtures
// generated by test_catalog_multipage_extraction.multipage_pdf at runtime.
export async function catalogMultipageExtraction({ page, expect, pdfPath, screenshotPath, manualMap = false, beforeConfirm }) {
  expect = expect.configure({ timeout: 60000 })
  const extracted = [], confirmed = []
  const observe = async response => {
    if (response.request().method() !== 'POST' || response.status() !== 200) return
    if (/\/reference-pages\/\d+\/extract$/.test(response.url())) extracted.push(await response.json())
    if (/\/reference-pages\/\d+\/extraction\/confirm$/.test(response.url())) confirmed.push(await response.json())
  }
  page.on('response', observe)
  const button = name => page.getByRole('button', { name, exact: true })
  await button('Нов каталог').click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Име на каталога', { exact: true }).fill('Synthetic QA multipage')
  await dialog.getByRole('combobox').selectOption({ label: 'Водоструйни машини с високо налягане' })
  await dialog.getByRole('button', { name: 'Продължи', exact: true }).click()
  await page.getByLabel('Референция', { exact: true }).fill('Synthetic QA reference')
  await button('Добави референция').click()
  await expect(page.getByLabel('Референция', { exact: true })).toHaveValue('')
  await button('Добави страница').click()
  const jump = async number => {
    await page.locator('.reader-toolbar input').fill(String(number))
    await page.locator('.reader-toolbar input').press('Enter')
    const image = page.getByRole('img', { name: `PDF страница ${number}`, exact: true })
    await expect(image).toBeVisible()
    await image.evaluate(image => image.decode())
  }
  await button('+ Добави схема').click()
  await page.getByLabel('Качи PDF', { exact: true }).setInputFiles(pdfPath)
  await jump(1)
  await button('Добави тази страница като схема').click()
  await expect(page.getByText('Страница 1 е добавена: Схема', { exact: true })).toBeVisible()
  await page.locator('.source-selection').getByRole('button', { name: 'Затвори', exact: true }).click()
  await button('+ Добави списък с части').click()
  for (const number of [2, 3]) {
    await jump(number)
    await button('Добави тази страница като списък с части').click()
    await expect(page.getByText(`Страница ${number} е добавена: Списъци с резервни части`, { exact: true })).toBeVisible()
  }
  await page.locator('.source-selection').getByRole('button', { name: 'Затвори', exact: true }).click()
  await page.locator('.page-workflow nav').getByRole('button', { name: 'Части', exact: true }).click()
  await page.locator('.guided-parts').getByRole('button', { name: 'Извлечи резервните части', exact: true }).click()
  await expect(page.getByLabel('Списъци с резервни части', { exact: true })).toContainText('Обработени източници: 2 / 2', { timeout: 120000 })
  if (manualMap) {
    await expect(page.getByLabel('Списъци с резервни части', { exact: true }).locator('[role=alert]')).toContainText('PDF страница 3')
    for (const [index, role] of ['position', 'part_number', 'description', 'quantity'].entries()) {
      await page.getByRole('combobox', { name: new RegExp(`^Колона ${index + 1}`) }).selectOption(role)
    }
    await page.getByRole('button', { name: 'Прочети таблицата отново', exact: true }).last().click()
  }
  await expect(page.locator('.guided-parts tbody tr')).toHaveCount(10)
  for (let position = 1; position <= 10; position++) {
    const row = page.getByRole('checkbox', { name: `Позиция ${position}`, exact: true })
    await expect(row).toBeVisible()
    await row.check() // Explicit human review includes inferred continuation rows.
  }
  await expect(page.getByLabel('Списъци с резервни части', { exact: true })).toContainText('Общо части: 10')
  await page.screenshot({ path: screenshotPath, fullPage: true })
  if (beforeConfirm) await beforeConfirm()
  await page.locator('.guided-parts').getByRole('button', { name: 'Потвърди избраните части', exact: true }).click()
  await expect(page.locator('.guided-parts').getByRole('button', { name: 'Потвърди избраните части', exact: true })).toBeDisabled()
  await expect(page.locator('.guided-parts > details').filter({ hasText: 'Преглед на части (10)' })).toBeVisible()
  await expect.poll(() => confirmed.reduce((total, result) => total + result.created_count, 0)).toBe(10)
  expect(extracted.map(result => result.source.page_number)).toEqual([2, 3])
  expect(extracted.map(result => result.rows.length)).toEqual(manualMap ? [5, 0] : [5, 5])
  page.off('response', observe)
  return { physicalPages: extracted.map(result => result.source.page_number), rowsPerPage: extracted.map(result => result.rows.length), accepted: 10, manualMap }
}
