import { type FormEvent, useEffect, useState } from 'react'
import { BookOpen, Search, Upload } from 'lucide-react'
import { api } from '../../api'
import { DownloadButton, Modal, filePayload, friendlyError } from '../../industrialUi'
import { useI18n, type TranslationKey } from '../../i18n'
import { hasPermission } from '../../permissions'
import type { TechnicalLibraryDocument } from '../../types'

export function TechnicalLibrary() {
  const { t } = useI18n()
  const [items, setItems] = useState<TechnicalLibraryDocument[]>([])
  const [query, setQuery] = useState('')
  const [error, setError] = useState('')
  const [showUpload, setShowUpload] = useState<'new' | number | null>(null)
  const load = () => api<TechnicalLibraryDocument[]>(`/technical-library?q=${encodeURIComponent(query)}`).then((data) => { setItems(data); setError('') }).catch((caught) => setError(friendlyError(caught, t('documents.loadError'))))
  useEffect(() => { void load() }, [query])
  const revisionTarget = typeof showUpload === 'number' ? items.find((item) => item.id === showUpload) : undefined
  return <><div className="toolbar"><div><h3>{t('documents.title')}</h3><p className="muted">{t('library.versionHint')}</p></div>{hasPermission('settings.manage') && <button className="primary" onClick={() => setShowUpload('new')}><Upload size={17} />{t('library.upload')}</button>}</div><div className="filters"><div className="searchbox"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('library.searchPlaceholder')} /></div></div>{error && <div className="error">{error}</div>}<div className="library-grid">{items.map((document) => <article className="panel library-card" key={document.id}><div className="library-card-head"><BookOpen /><span><h4>{document.title}</h4><small>{document.brand} · {document.model || document.category}</small></span></div><div className="library-meta"><span>{t('library.revision')}: {document.revision || t('common.noValue')}</span><span>{t('library.versions', { count: document.revisions.length })}</span>{document.language && <span>{t(`language.${document.language}` as TranslationKey)}</span>}{document.page_count && <span>{t('library.pages', { count: document.page_count })}</span>}{document.linked_machine_numbers?.length ? <span>{t('library.linkedMachineCount', { count: document.linked_machine_numbers.length })}</span> : null}{document.tags?.map((tag) => <span className="badge" key={tag}>{tag}</span>)}{document.sha256 && <code>SHA-256 {document.sha256.slice(0, 12)}…</code>}</div>{document.source_label && <p className="muted">{t('library.source')}: {document.source_label}</p>}<div className="actions"><DownloadButton path={document.download_endpoint} filename={document.title} />{hasPermission('settings.manage') && <button className="secondary compact" onClick={() => setShowUpload(document.id)}><Upload size={15} />{t('library.newRevision')}</button>}</div><details><summary>{t('library.versionHistory')}</summary>{document.revisions.map((revision) => <div className="revision-row" key={revision.id}><span><b>v{revision.version} · {revision.revision_label || t('common.noValue')}</b><small>{revision.change_note}</small></span><DownloadButton path={revision.download_endpoint} filename={revision.filename} /></div>)}</details></article>)}{!items.length && <div className="empty-state">{t('documents.empty')}</div>}</div>{showUpload && <TechnicalUploadModal document={revisionTarget} onClose={() => setShowUpload(null)} onSaved={() => { setShowUpload(null); void load() }} />}</>
}

function TechnicalUploadModal({ document, onClose, onSaved }: { document?: TechnicalLibraryDocument; onClose: () => void; onSaved: () => void }) {
  const { locale, t } = useI18n()
  const [form, setForm] = useState({ brand: document?.brand || '', model: document?.model || '', category: document?.category || '', title: document?.title || '', revision: '', change_note: '', source_label: document?.source_label || '', document_date: document?.document_date?.slice(0, 10) || '', tags_text: document?.tags?.join(', ') || '', page_count: document?.page_count ? String(document.page_count) : '', notes: document?.notes || '', linked_machine_numbers_text: document?.linked_machine_numbers?.join(', ') || '' })
  const [file, setFile] = useState<File | null>(null)
  const [error, setError] = useState('')
  async function submit(event: FormEvent) {
    event.preventDefault()
    if (!file) return
    const path = document ? `/technical-library/${document.id}/revisions` : '/technical-library'
    const { tags_text, linked_machine_numbers_text, ...values } = form
    try { await api(path, { method: 'POST', body: JSON.stringify({ ...values, language: locale, document_date: form.document_date || null, page_count: form.page_count ? Number(form.page_count) : null, tags: tags_text.split(',').map((item) => item.trim()).filter(Boolean), linked_machine_numbers: linked_machine_numbers_text.split(/[;,\s]+/).map((item) => item.trim()).filter(Boolean), ...(await filePayload(file)) }) }); onSaved() } catch (caught) { setError(friendlyError(caught, t('library.uploadError'))) }
  }
  return <Modal title={document ? t('library.newRevision') : t('library.upload')} onClose={onClose} wide><form className="form-grid" onSubmit={submit}><label>{t('machines.brand')}<input required disabled={Boolean(document)} value={form.brand} onChange={(event) => setForm({ ...form, brand: event.target.value })} /></label><label>{t('machines.model')}<input disabled={Boolean(document)} value={form.model} onChange={(event) => setForm({ ...form, model: event.target.value })} /></label><label>{t('machines.category')}<input required disabled={Boolean(document)} value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} /></label><label>{t('library.revision')}<input required value={form.revision} onChange={(event) => setForm({ ...form, revision: event.target.value })} /></label><label className="wide">{t('library.title')}<input required disabled={Boolean(document)} value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>{t('library.source')}<input value={form.source_label} onChange={(event) => setForm({ ...form, source_label: event.target.value })} /></label><label>{t('library.documentDate')}<input type="date" value={form.document_date} onChange={(event) => setForm({ ...form, document_date: event.target.value })} /></label><label>{t('library.pageCount')}<input type="number" min="1" value={form.page_count} onChange={(event) => setForm({ ...form, page_count: event.target.value })} /></label><label>{t('library.tags')}<input value={form.tags_text} onChange={(event) => setForm({ ...form, tags_text: event.target.value })} /></label><label className="wide">{t('library.linkedMachines')}<input value={form.linked_machine_numbers_text} onChange={(event) => setForm({ ...form, linked_machine_numbers_text: event.target.value })} placeholder={t('catalog.compatibleMachinesHint')} /></label><label className="wide">{t('common.notes')}<textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label><label className="wide">{t('library.changeNote')}<textarea required={Boolean(document)} value={form.change_note} onChange={(event) => setForm({ ...form, change_note: event.target.value })} /></label><label className="wide">{t('library.file')}<input required type="file" accept="application/pdf,.docx,.xlsx,image/png,image/jpeg,image/webp" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label>{error && <div className="error wide">{error}</div>}<div className="actions wide"><button type="button" className="secondary" onClick={onClose}>{t('common.cancel')}</button><button className="primary" disabled={!file}>{document ? t('library.addRevision') : t('library.upload')}</button></div></form></Modal>
}
