import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
// Exercise the public import before and after extraction with the real API client.
import BulkTransfers, { CancelBatchModal, IssueModal, ReturnModal } from '../../../BulkTransfers'
import { setSessionUser } from '../../../permissions'
import type { UserSession } from '../../../types'
import { change, checklist, deferred, details, fillIssue, fillReturn, issued, issueResult, locations, machines, mockApi, response, returnFields, returnResult, t } from './fixtures'

afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals() })

describe('bulk transfer HTTP and state contracts (characterized before extraction)', () => {
  it('keeps keyboard selection across search, trusts available rather than status, and edits the checklist before confirmation', async () => {
    const user = userEvent.setup()
    const request = mockApi(() => response(issueResult(), 201))
    const onComplete = vi.fn()
    render(<IssueModal items={machines} locations={locations} onClose={vi.fn()} onComplete={onComplete} />)
    const first = screen.getByLabelText('Машина №4')
    first.focus()
    await user.keyboard(' ')
    expect(first).toBeChecked()
    expect(screen.getByLabelText('Машина №7')).toBeDisabled() // READY but unavailable at the server.
    expect(screen.getByText('Тестов pending transfer от API.')).toBeVisible()
    change(t('bulk.machineSearch'), '5')
    await user.click(screen.getByLabelText('Машина №5'))
    change(t('bulk.machineSearch'), '')
    expect(screen.getByLabelText('Машина №4')).toBeChecked()
    expect(screen.getByText('Избрани машини: 2')).toBeVisible()
    expect(screen.queryByRole('option', { name: 'QA inactive' })).not.toBeInTheDocument()
    fillIssue()
    const pump = screen.getByText(t('bulk.checklist.item.pump')).closest<HTMLElement>('.checklist-row')!
    await user.selectOptions(within(pump).getByRole('combobox'), 'SATISFACTORY')
    fireEvent.change(within(pump).getByRole('textbox'), { target: { value: ' QA note ' } })
    fireEvent.change(screen.getAllByPlaceholderText(t('bulk.checklist.lengthPlaceholder'))[0], { target: { value: '0' } })
    fireEvent.change(screen.getAllByPlaceholderText(t('bulk.checklist.lengthPlaceholder'))[1], { target: { value: '25.5' } })
    await user.click(screen.getByRole('button', { name: t('bulk.reviewConfirm') }))
    expect(request).not.toHaveBeenCalled()
    expect(screen.getByRole('region', { name: t('bulk.issueConfirmTitle') })).toHaveTextContent('№4, №5')
    await user.click(screen.getByRole('button', { name: t('common.back') }))
    expect(screen.getByLabelText('Машина №4')).toBeChecked()
    expect(within(screen.getByText(t('bulk.checklist.item.pump')).closest('.checklist-row')!).getByRole('combobox')).toHaveValue('SATISFACTORY')
    await user.click(screen.getByRole('button', { name: t('bulk.reviewConfirm') }))
    await user.click(screen.getByRole('button', { name: t('bulk.confirmIssue') }))
    await screen.findByRole('heading', { name: t('bulk.issueSuccess') })
    const expected = checklist()
    expected[0] = { ...expected[0], condition: 'SATISFACTORY', note: ' QA note ' }
    expected[1].length_m = 0
    expected[2].length_m = 25.5
    expect(request).toHaveBeenCalledTimes(1)
    expect(request).toHaveBeenCalledWith('/api/transfers/bulk-issue', expect.objectContaining({
      method: 'POST', credentials: 'same-origin', body: JSON.stringify({
        machine_ids: [1, 2], document_language: 'bg', usage_text: 'QA usage', location_id: 1,
        condition_text: 'QA condition', remarks: null, checklist: expected,
        recipient: { first_name: 'Тестов', middle_name: 'Външен', last_name: 'Получател', is_foreign_person: false, name_exception_reason: null },
      }),
    }))
    expect(new Headers(request.mock.calls[0][1]?.headers).get('Accept-Language')).toBe('bg')
    expect(onComplete).toHaveBeenCalledTimes(1)
    expect(screen.getAllByRole('button', { name: 'DOCX' })).toHaveLength(2)
    expect(screen.getAllByRole('button', { name: 'PDF' })).toHaveLength(2)
    expect(screen.getByRole('button', { name: t('bulk.downloadAllZip') })).toBeEnabled()
  })

  it('keeps the foreign-name exception validation and original untrimmed recipient fields', async () => {
    const user = userEvent.setup()
    const request = mockApi(() => response(issueResult(), 201))
    render(<IssueModal items={machines} locations={locations} onClose={vi.fn()} onComplete={vi.fn()} />)
    await user.click(screen.getByLabelText('Машина №4'))
    fillIssue()
    change(t('profile.firstName'), ' QA ')
    change(t('profile.middleName'), '')
    await user.click(screen.getByLabelText(t('bulk.foreignPerson')))
    change(t('profile.exceptionReason'), 'short')
    await user.click(screen.getByRole('button', { name: t('bulk.reviewConfirm') }))
    expect(screen.getByRole('alert')).toHaveTextContent(t('bulk.recipientRequired'))
    expect(request).not.toHaveBeenCalled()
    change(t('profile.exceptionReason'), ' QA documented exception ')
    await user.click(screen.getByRole('button', { name: t('bulk.reviewConfirm') }))
    await user.click(screen.getByRole('button', { name: t('bulk.confirmIssue') }))
    await waitFor(() => expect(request).toHaveBeenCalledTimes(1))
    expect(JSON.parse(String(request.mock.calls[0][1]?.body)).recipient).toEqual({ first_name: ' QA ', middle_name: null, last_name: 'Получател', is_foreign_person: true, name_exception_reason: ' QA documented exception ' })
  })

  it('blocks duplicate pending submits and preserves the confirmation and selection after a structured issue conflict', async () => {
    const user = userEvent.setup()
    const pending = deferred<Response>()
    const request = mockApi(() => pending.promise)
    const onComplete = vi.fn()
    render(<IssueModal items={machines} locations={locations} onClose={vi.fn()} onComplete={onComplete} />)
    await user.click(screen.getByLabelText('Машина №4'))
    fillIssue()
    await user.click(screen.getByRole('button', { name: t('bulk.reviewConfirm') }))
    await user.dblClick(screen.getByRole('button', { name: t('bulk.confirmIssue') }))
    expect(request).toHaveBeenCalledTimes(1)
    expect(screen.getByRole('button', { name: t('bulk.issuing') })).toBeDisabled()
    expect(screen.getByRole('button', { name: t('common.back') })).toBeDisabled()
    await act(async () => pending.resolve(response({ detail: { code: 'issue_conflict', message: 'Internal detail', conflicts: [{ machine_number: '4', status: 'ISSUED', protocol_number: 'QA-ISSUE', current_recipient_or_location: 'QA recipient' }] } }, 409)))
    expect(await screen.findByRole('alert')).toHaveTextContent(t('errors.issueConflict'))
    expect(screen.getByRole('alert')).toHaveTextContent('QA-ISSUE')
    expect(screen.getByRole('alert')).not.toHaveTextContent('Internal detail')
    expect(onComplete).not.toHaveBeenCalled()
    await user.click(screen.getByRole('button', { name: t('common.back') }))
    expect(screen.getByLabelText('Машина №4')).toBeChecked()
    expect(screen.getByLabelText(t('bulk.usageText'))).toHaveValue('  QA usage  ')
  })

  it('closes an unsubmitted issue without a mutation and renders network failures generically', async () => {
    const user = userEvent.setup()
    const close = vi.fn()
    const request = mockApi(() => { throw new Error('private network diagnostic') })
    render(<IssueModal items={machines} locations={locations} onClose={close} onComplete={vi.fn()} />)
    await user.click(screen.getByRole('button', { name: t('common.cancel') }))
    expect(close).toHaveBeenCalledTimes(1)
    expect(request).not.toHaveBeenCalled()
    await user.click(screen.getByLabelText('Машина №4'))
    fillIssue()
    await user.click(screen.getByRole('button', { name: t('bulk.reviewConfirm') }))
    await user.click(screen.getByRole('button', { name: t('bulk.confirmIssue') }))
    expect(await screen.findByRole('alert')).toHaveTextContent(t('errors.generic'))
    expect(screen.queryByText('private network diagnostic')).not.toBeInTheDocument()
  })

  it('keeps independent return drafts across filtering and sends only the selected active transfer IDs with unchanged READY/REPAIR fields', async () => {
    const user = userEvent.setup()
    const request = mockApi(() => response(returnResult()))
    render(<ReturnModal items={[...issued, machines[2]]} onClose={vi.fn()} onComplete={vi.fn()} />)
    expect(screen.queryByLabelText('Връщане на машина №7')).not.toBeInTheDocument()
    await user.click(screen.getByLabelText('Връщане на машина №5'))
    fillReturn('5')
    await user.click(screen.getByLabelText('Връщане на машина №4'))
    fillReturn('4')
    const first = returnFields('4')
    await user.click(first.getByRole('radio', { name: t('bulk.outcomeRepair') }))
    fireEvent.change(first.getByLabelText(t('bulk.missingEquipment')), { target: { value: ' QA missing ' } })
    fireEvent.change(first.getByLabelText(t('bulk.damage')), { target: { value: ' QA damage ' } })
    fireEvent.change(first.getByLabelText(t('bulk.contamination')), { target: { value: ' QA dirt ' } })
    fireEvent.change(first.getByLabelText(t('common.notes')), { target: { value: ' QA note ' } })
    const pump = within(first.getByText(t('bulk.checklist.item.pump')).closest('.checklist-row')!)
    await user.selectOptions(pump.getByRole('combobox'), 'REPAIR')
    expect(within(returnFields('5').getByText(t('bulk.checklist.item.pump')).closest('.checklist-row')!).getByRole('combobox')).toHaveValue('GOOD')
    change(t('bulk.returnSearch'), 'QA-ISSUE-2')
    expect(screen.queryByLabelText('Връщане на машина №4')).not.toBeInTheDocument()
    expect(screen.getByText('Избрани машини: 2')).toBeVisible()
    change(t('bulk.returnSearch'), '')
    expect(returnFields('4').getByRole('radio', { name: t('bulk.outcomeRepair') })).toBeChecked()
    await user.click(screen.getByRole('button', { name: t('bulk.reviewConfirm') }))
    expect(request).not.toHaveBeenCalled()
    await user.click(screen.getByRole('button', { name: t('bulk.confirmReturn') }))
    await waitFor(() => expect(request).toHaveBeenCalledTimes(1))
    const firstChecklist = checklist()
    firstChecklist[0].condition = 'REPAIR'
    expect(request).toHaveBeenCalledWith('/api/transfers/bulk-return', expect.objectContaining({ method: 'POST', credentials: 'same-origin' }))
    expect(JSON.parse(String(request.mock.calls[0][1]?.body))).toEqual({ document_language: 'bg', items: [
      { transfer_id: 101, machine_id: 1, condition_text: ' QA condition 4 ', result_text: ' QA result 4 ', notes: ' QA note ', missing_equipment: ' QA missing ', damage: ' QA damage ', contamination: ' QA dirt ', next_status: 'REPAIR', checklist: firstChecklist },
      { transfer_id: 102, machine_id: 2, condition_text: ' QA condition 5 ', result_text: ' QA result 5 ', notes: '', missing_equipment: '', damage: '', contamination: '', next_status: 'READY', checklist: checklist() },
    ] })
  })

  it('resets only a deselected return draft and displays the server partial-return result without inventing documents', async () => {
    const user = userEvent.setup()
    const done = vi.fn()
    const result = returnResult()
    const request = mockApi(() => response(result))
    render(<ReturnModal items={issued} onClose={vi.fn()} onComplete={done} />)
    await user.click(screen.getByLabelText('Връщане на машина №4'))
    fillReturn('4')
    await user.click(returnFields('4').getByRole('radio', { name: t('bulk.outcomeRepair') }))
    await user.click(screen.getByLabelText('Връщане на машина №5'))
    fillReturn('5')
    await user.click(screen.getByLabelText('Връщане на машина №5'))
    await user.click(screen.getByLabelText('Връщане на машина №5'))
    expect(returnFields('5').getByLabelText(t('bulk.returnCondition'))).toHaveValue('')
    expect(returnFields('4').getByLabelText(t('bulk.returnCondition'))).toHaveValue(' QA condition 4 ')
    await user.click(screen.getByLabelText('Връщане на машина №5'))
    await user.click(screen.getByRole('button', { name: t('bulk.reviewConfirm') }))
    await user.click(screen.getByRole('button', { name: t('bulk.confirmReturn') }))
    expect(await screen.findByText(t('batch.partiallyReturned'))).toBeVisible()
    expect(screen.getByText(/Все още издадени: 1/)).toBeVisible()
    expect(screen.getAllByRole('button', { name: 'DOCX' })).toHaveLength(1)
    expect(screen.getAllByRole('button', { name: 'PDF' })).toHaveLength(1)
    expect(JSON.parse(String(request.mock.calls[0][1]?.body)).items.map((item: { transfer_id: number }) => item.transfer_id)).toEqual([101])
    expect(done).toHaveBeenCalledTimes(1)
  })

  it('retains return fields and the structured conflict after a rejected atomic return', async () => {
    const user = userEvent.setup()
    const request = mockApi(() => response({ detail: { code: 'return_conflict', conflicts: [{ machine_number: '4', protocol_number: 'QA-ISSUE-1' }] } }, 409))
    const done = vi.fn()
    render(<ReturnModal items={issued} onClose={vi.fn()} onComplete={done} />)
    await user.click(screen.getByLabelText('Връщане на машина №4'))
    fillReturn('4')
    await user.click(screen.getByRole('button', { name: t('bulk.reviewConfirm') }))
    await user.click(screen.getByRole('button', { name: t('bulk.confirmReturn') }))
    expect(await screen.findByRole('alert')).toHaveTextContent(t('errors.returnConflict'))
    expect(screen.getByRole('alert')).toHaveTextContent('QA-ISSUE-1')
    await user.click(screen.getByRole('button', { name: t('common.back') }))
    expect(screen.getByLabelText('Връщане на машина №4')).toBeChecked()
    expect(returnFields('4').getByLabelText(t('bulk.returnResult'))).toHaveValue(' QA result 4 ')
    expect(done).not.toHaveBeenCalled()
    expect(request).toHaveBeenCalledTimes(1)
  })

  it.each([[403, 'permission_denied', 'errors.permissionDenied'], [409, 'batch_not_pending', 'errors.batchNotPending']] as const)('keeps cancellation reason visible after HTTP %s and prevents a second in-flight cancellation', async (status, code, key) => {
    const user = userEvent.setup()
    const pending = deferred<Response>()
    const request = mockApi(() => pending.promise)
    const close = vi.fn()
    const cancelled = vi.fn()
    render(<CancelBatchModal batch={details()} onClose={close} onCancelled={cancelled} />)
    change(t('bulk.cancelReason'), '  QA cancellation  ')
    await user.dblClick(screen.getByRole('button', { name: t('bulk.cancelConfirm') }))
    expect(request).toHaveBeenCalledTimes(1)
    await user.click(screen.getByRole('button', { name: t('common.close') }))
    expect(close).not.toHaveBeenCalled()
    await act(async () => pending.resolve(response({ detail: { code, message: 'not for display' } }, status)))
    expect(screen.getAllByRole('alert').at(-1)).toHaveTextContent(t(key))
    expect(screen.getByLabelText(t('bulk.cancelReason'))).toHaveValue('  QA cancellation  ')
    expect(request.mock.calls[0][1]?.body).toBe(JSON.stringify({ reason: 'QA cancellation' }))
    expect(cancelled).not.toHaveBeenCalled()
  })

  it('loads the authoritative workspace and refreshes availability/history only after cancellation succeeds', async () => {
    setSessionUser({ permissions: ['transfers.view', 'transfers.create', 'transfers.return'], preferred_language: 'bg' } as UserSession)
    const user = userEvent.setup()
    const done = vi.fn()
    const request = mockApi((path, init) => {
      if (path === '/api/transfers/availability') return response(machines)
      if (path === '/api/locations') return response(locations)
      if (path === '/api/transfer-batches') {
        // The summary response has no individual transfer rows.
        return response([{ ...details(), transfers: undefined }])
      }
      if (path === '/api/transfer-batches/11') return response(details())
      if (path === '/api/transfer-batches/11/cancel' && init.method === 'POST') return response({ batch_id: 11, batch_reference: 'QA-BATCH', status: 'CANCELLED', cancelled_transfers: 2, invalidated_signing_sessions: 2, message: 'QA' })
      throw new Error('Unexpected test request')
    })
    render(<BulkTransfers onChanged={done} />)
    await screen.findByRole('heading', { name: '№4, №5' })
    expect(request.mock.calls.map(([path]) => path)).toEqual(['/api/transfers/availability', '/api/locations', '/api/transfer-batches'])
    await user.click(screen.getByRole('button', { name: t('bulk.cancelPendingAction') }))
    await screen.findByLabelText(t('bulk.cancelReason'))
    expect(done).not.toHaveBeenCalled()
    change(t('bulk.cancelReason'), 'QA reason')
    await user.click(screen.getByRole('button', { name: t('bulk.cancelConfirm') }))
    await waitFor(() => expect(done).toHaveBeenCalledTimes(1))
    expect(request.mock.calls.map(([path]) => path)).toEqual(['/api/transfers/availability', '/api/locations', '/api/transfer-batches', '/api/transfer-batches/11', '/api/transfer-batches/11/cancel', '/api/transfers/availability', '/api/locations', '/api/transfer-batches'])
  })

  it('keeps read-only workspace controls unavailable without transfer permissions', async () => {
    const request = mockApi(path => response(path === '/api/transfer-batches' ? [details()] : []))
    render(<BulkTransfers onChanged={vi.fn()} />)
    await screen.findByRole('heading', { name: '№4, №5' })
    expect(screen.queryByRole('button', { name: t('bulk.issue') })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: t('bulk.return') })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: t('bulk.cancelPendingAction') })).not.toBeInTheDocument()
    expect(request.mock.calls.every(([, init]) => !init?.method)).toBe(true)
  })
})
